#!/usr/bin/env bash

case "$1" in
  get-workspaces)
    niri msg --json workspaces | jq '
      map({
        id: (.id | tostring),
        is_focused: (.is_focused),
        text: (
          if .idx == 1 then ""
          elif .idx == 2 then ""
          elif .idx == 3 then ""
          elif .idx == 4 then ""
          elif .idx == 5 then ""
          else "●"
          end
        )
      })| sort_by(.id)
    '
    ;;

  get-active)
    niri msg --json workspaces \
      | jq -r '.[] | select(.is_focused) | .id'
    ;;

  set-active)
    niri msg action focus-workspace "$2"
    ;;
esac
