#! /bin/sh

# Set wallpaper
"$HOME"/Scripts/change_wallpaper.sh

# Launch services
"$HOME"/.config/picom/launch.sh &
"$HOME"/.config/sxhkd/launch.sh &
"$HOME"/.config/eww/launch.sh &
"$HOME"/.config/dunst/launch.sh &
openrgb -p BlueThunder.orp &

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.66
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config single_monocle true
bspc config left_monocle_padding 1000
bspc config right_monocle_padding 1000
bspc config top_monocle_padding 5
bspc config bottom_monocle_padding 5

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Pavucontrol state=floating rectangle=789x512+264+130
