#! /bin/sh

$HOME/.config/compton/launch.sh &
$HOME/.config/sxhkd/launch.sh &
$HOME/.config/polybar/launch.sh &

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc monitor -d 1 2 3 4 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a code-oss desktop='^3' follow=on
